// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: diztl.proto

package io.github.gravetii.grpc;

public interface DisconnectReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:DisconnectReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.Node node = 1;</code>
   */
  boolean hasNode();
  /**
   * <code>.Node node = 1;</code>
   */
  io.github.gravetii.grpc.Node getNode();
  /**
   * <code>.Node node = 1;</code>
   */
  io.github.gravetii.grpc.NodeOrBuilder getNodeOrBuilder();
}
