// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: diztl.proto

package io.github.gravetii.grpc;

public interface FetchFileListReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:FetchFileListReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.Node node = 1;</code>
   */
  boolean hasNode();
  /**
   * <code>.Node node = 1;</code>
   */
  io.github.gravetii.grpc.Node getNode();
  /**
   * <code>.Node node = 1;</code>
   */
  io.github.gravetii.grpc.NodeOrBuilder getNodeOrBuilder();

  /**
   * <code>string dir = 2;</code>
   */
  java.lang.String getDir();
  /**
   * <code>string dir = 2;</code>
   */
  com.google.protobuf.ByteString
      getDirBytes();
}
