// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: diztl.proto

package io.github.gravetii.grpc;

public interface GetFileListRespOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetFileListResp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .FileMetadata files = 1;</code>
   */
  java.util.List<io.github.gravetii.grpc.FileMetadata> 
      getFilesList();
  /**
   * <code>repeated .FileMetadata files = 1;</code>
   */
  io.github.gravetii.grpc.FileMetadata getFiles(int index);
  /**
   * <code>repeated .FileMetadata files = 1;</code>
   */
  int getFilesCount();
  /**
   * <code>repeated .FileMetadata files = 1;</code>
   */
  java.util.List<? extends io.github.gravetii.grpc.FileMetadataOrBuilder> 
      getFilesOrBuilderList();
  /**
   * <code>repeated .FileMetadata files = 1;</code>
   */
  io.github.gravetii.grpc.FileMetadataOrBuilder getFilesOrBuilder(
      int index);
}
