// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: diztl.proto

package io.github.gravetii.grpc;

public interface GetTrackerReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetTrackerReq)
    com.google.protobuf.MessageOrBuilder {
}
