// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: diztl.proto

package io.github.gravetii.grpc;

/**
 * Protobuf type {@code PingReq}
 */
public  final class PingReq extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:PingReq)
    PingReqOrBuilder {
private static final long serialVersionUID = 0L;
  // Use PingReq.newBuilder() to construct.
  private PingReq(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private PingReq() {
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private PingReq(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            io.github.gravetii.grpc.Node.Builder subBuilder = null;
            if (source_ != null) {
              subBuilder = source_.toBuilder();
            }
            source_ = input.readMessage(io.github.gravetii.grpc.Node.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(source_);
              source_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            io.github.gravetii.grpc.Node.Builder subBuilder = null;
            if (dest_ != null) {
              subBuilder = dest_.toBuilder();
            }
            dest_ = input.readMessage(io.github.gravetii.grpc.Node.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(dest_);
              dest_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.github.gravetii.grpc.Diztl.internal_static_PingReq_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.github.gravetii.grpc.Diztl.internal_static_PingReq_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.github.gravetii.grpc.PingReq.class, io.github.gravetii.grpc.PingReq.Builder.class);
  }

  public static final int SOURCE_FIELD_NUMBER = 1;
  private io.github.gravetii.grpc.Node source_;
  /**
   * <code>.Node source = 1;</code>
   */
  public boolean hasSource() {
    return source_ != null;
  }
  /**
   * <code>.Node source = 1;</code>
   */
  public io.github.gravetii.grpc.Node getSource() {
    return source_ == null ? io.github.gravetii.grpc.Node.getDefaultInstance() : source_;
  }
  /**
   * <code>.Node source = 1;</code>
   */
  public io.github.gravetii.grpc.NodeOrBuilder getSourceOrBuilder() {
    return getSource();
  }

  public static final int DEST_FIELD_NUMBER = 2;
  private io.github.gravetii.grpc.Node dest_;
  /**
   * <code>.Node dest = 2;</code>
   */
  public boolean hasDest() {
    return dest_ != null;
  }
  /**
   * <code>.Node dest = 2;</code>
   */
  public io.github.gravetii.grpc.Node getDest() {
    return dest_ == null ? io.github.gravetii.grpc.Node.getDefaultInstance() : dest_;
  }
  /**
   * <code>.Node dest = 2;</code>
   */
  public io.github.gravetii.grpc.NodeOrBuilder getDestOrBuilder() {
    return getDest();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (source_ != null) {
      output.writeMessage(1, getSource());
    }
    if (dest_ != null) {
      output.writeMessage(2, getDest());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (source_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getSource());
    }
    if (dest_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getDest());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.github.gravetii.grpc.PingReq)) {
      return super.equals(obj);
    }
    io.github.gravetii.grpc.PingReq other = (io.github.gravetii.grpc.PingReq) obj;

    boolean result = true;
    result = result && (hasSource() == other.hasSource());
    if (hasSource()) {
      result = result && getSource()
          .equals(other.getSource());
    }
    result = result && (hasDest() == other.hasDest());
    if (hasDest()) {
      result = result && getDest()
          .equals(other.getDest());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasSource()) {
      hash = (37 * hash) + SOURCE_FIELD_NUMBER;
      hash = (53 * hash) + getSource().hashCode();
    }
    if (hasDest()) {
      hash = (37 * hash) + DEST_FIELD_NUMBER;
      hash = (53 * hash) + getDest().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.github.gravetii.grpc.PingReq parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.github.gravetii.grpc.PingReq parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.github.gravetii.grpc.PingReq parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.github.gravetii.grpc.PingReq parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.github.gravetii.grpc.PingReq parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.github.gravetii.grpc.PingReq parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.github.gravetii.grpc.PingReq parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.github.gravetii.grpc.PingReq parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.github.gravetii.grpc.PingReq parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.github.gravetii.grpc.PingReq parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.github.gravetii.grpc.PingReq parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.github.gravetii.grpc.PingReq parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.github.gravetii.grpc.PingReq prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code PingReq}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:PingReq)
      io.github.gravetii.grpc.PingReqOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.github.gravetii.grpc.Diztl.internal_static_PingReq_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.github.gravetii.grpc.Diztl.internal_static_PingReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.github.gravetii.grpc.PingReq.class, io.github.gravetii.grpc.PingReq.Builder.class);
    }

    // Construct using io.github.gravetii.grpc.PingReq.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (sourceBuilder_ == null) {
        source_ = null;
      } else {
        source_ = null;
        sourceBuilder_ = null;
      }
      if (destBuilder_ == null) {
        dest_ = null;
      } else {
        dest_ = null;
        destBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.github.gravetii.grpc.Diztl.internal_static_PingReq_descriptor;
    }

    @java.lang.Override
    public io.github.gravetii.grpc.PingReq getDefaultInstanceForType() {
      return io.github.gravetii.grpc.PingReq.getDefaultInstance();
    }

    @java.lang.Override
    public io.github.gravetii.grpc.PingReq build() {
      io.github.gravetii.grpc.PingReq result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.github.gravetii.grpc.PingReq buildPartial() {
      io.github.gravetii.grpc.PingReq result = new io.github.gravetii.grpc.PingReq(this);
      if (sourceBuilder_ == null) {
        result.source_ = source_;
      } else {
        result.source_ = sourceBuilder_.build();
      }
      if (destBuilder_ == null) {
        result.dest_ = dest_;
      } else {
        result.dest_ = destBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.github.gravetii.grpc.PingReq) {
        return mergeFrom((io.github.gravetii.grpc.PingReq)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.github.gravetii.grpc.PingReq other) {
      if (other == io.github.gravetii.grpc.PingReq.getDefaultInstance()) return this;
      if (other.hasSource()) {
        mergeSource(other.getSource());
      }
      if (other.hasDest()) {
        mergeDest(other.getDest());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      io.github.gravetii.grpc.PingReq parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (io.github.gravetii.grpc.PingReq) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private io.github.gravetii.grpc.Node source_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        io.github.gravetii.grpc.Node, io.github.gravetii.grpc.Node.Builder, io.github.gravetii.grpc.NodeOrBuilder> sourceBuilder_;
    /**
     * <code>.Node source = 1;</code>
     */
    public boolean hasSource() {
      return sourceBuilder_ != null || source_ != null;
    }
    /**
     * <code>.Node source = 1;</code>
     */
    public io.github.gravetii.grpc.Node getSource() {
      if (sourceBuilder_ == null) {
        return source_ == null ? io.github.gravetii.grpc.Node.getDefaultInstance() : source_;
      } else {
        return sourceBuilder_.getMessage();
      }
    }
    /**
     * <code>.Node source = 1;</code>
     */
    public Builder setSource(io.github.gravetii.grpc.Node value) {
      if (sourceBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        source_ = value;
        onChanged();
      } else {
        sourceBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.Node source = 1;</code>
     */
    public Builder setSource(
        io.github.gravetii.grpc.Node.Builder builderForValue) {
      if (sourceBuilder_ == null) {
        source_ = builderForValue.build();
        onChanged();
      } else {
        sourceBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.Node source = 1;</code>
     */
    public Builder mergeSource(io.github.gravetii.grpc.Node value) {
      if (sourceBuilder_ == null) {
        if (source_ != null) {
          source_ =
            io.github.gravetii.grpc.Node.newBuilder(source_).mergeFrom(value).buildPartial();
        } else {
          source_ = value;
        }
        onChanged();
      } else {
        sourceBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.Node source = 1;</code>
     */
    public Builder clearSource() {
      if (sourceBuilder_ == null) {
        source_ = null;
        onChanged();
      } else {
        source_ = null;
        sourceBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.Node source = 1;</code>
     */
    public io.github.gravetii.grpc.Node.Builder getSourceBuilder() {
      
      onChanged();
      return getSourceFieldBuilder().getBuilder();
    }
    /**
     * <code>.Node source = 1;</code>
     */
    public io.github.gravetii.grpc.NodeOrBuilder getSourceOrBuilder() {
      if (sourceBuilder_ != null) {
        return sourceBuilder_.getMessageOrBuilder();
      } else {
        return source_ == null ?
            io.github.gravetii.grpc.Node.getDefaultInstance() : source_;
      }
    }
    /**
     * <code>.Node source = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        io.github.gravetii.grpc.Node, io.github.gravetii.grpc.Node.Builder, io.github.gravetii.grpc.NodeOrBuilder> 
        getSourceFieldBuilder() {
      if (sourceBuilder_ == null) {
        sourceBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            io.github.gravetii.grpc.Node, io.github.gravetii.grpc.Node.Builder, io.github.gravetii.grpc.NodeOrBuilder>(
                getSource(),
                getParentForChildren(),
                isClean());
        source_ = null;
      }
      return sourceBuilder_;
    }

    private io.github.gravetii.grpc.Node dest_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        io.github.gravetii.grpc.Node, io.github.gravetii.grpc.Node.Builder, io.github.gravetii.grpc.NodeOrBuilder> destBuilder_;
    /**
     * <code>.Node dest = 2;</code>
     */
    public boolean hasDest() {
      return destBuilder_ != null || dest_ != null;
    }
    /**
     * <code>.Node dest = 2;</code>
     */
    public io.github.gravetii.grpc.Node getDest() {
      if (destBuilder_ == null) {
        return dest_ == null ? io.github.gravetii.grpc.Node.getDefaultInstance() : dest_;
      } else {
        return destBuilder_.getMessage();
      }
    }
    /**
     * <code>.Node dest = 2;</code>
     */
    public Builder setDest(io.github.gravetii.grpc.Node value) {
      if (destBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        dest_ = value;
        onChanged();
      } else {
        destBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.Node dest = 2;</code>
     */
    public Builder setDest(
        io.github.gravetii.grpc.Node.Builder builderForValue) {
      if (destBuilder_ == null) {
        dest_ = builderForValue.build();
        onChanged();
      } else {
        destBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.Node dest = 2;</code>
     */
    public Builder mergeDest(io.github.gravetii.grpc.Node value) {
      if (destBuilder_ == null) {
        if (dest_ != null) {
          dest_ =
            io.github.gravetii.grpc.Node.newBuilder(dest_).mergeFrom(value).buildPartial();
        } else {
          dest_ = value;
        }
        onChanged();
      } else {
        destBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.Node dest = 2;</code>
     */
    public Builder clearDest() {
      if (destBuilder_ == null) {
        dest_ = null;
        onChanged();
      } else {
        dest_ = null;
        destBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.Node dest = 2;</code>
     */
    public io.github.gravetii.grpc.Node.Builder getDestBuilder() {
      
      onChanged();
      return getDestFieldBuilder().getBuilder();
    }
    /**
     * <code>.Node dest = 2;</code>
     */
    public io.github.gravetii.grpc.NodeOrBuilder getDestOrBuilder() {
      if (destBuilder_ != null) {
        return destBuilder_.getMessageOrBuilder();
      } else {
        return dest_ == null ?
            io.github.gravetii.grpc.Node.getDefaultInstance() : dest_;
      }
    }
    /**
     * <code>.Node dest = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        io.github.gravetii.grpc.Node, io.github.gravetii.grpc.Node.Builder, io.github.gravetii.grpc.NodeOrBuilder> 
        getDestFieldBuilder() {
      if (destBuilder_ == null) {
        destBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            io.github.gravetii.grpc.Node, io.github.gravetii.grpc.Node.Builder, io.github.gravetii.grpc.NodeOrBuilder>(
                getDest(),
                getParentForChildren(),
                isClean());
        dest_ = null;
      }
      return destBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:PingReq)
  }

  // @@protoc_insertion_point(class_scope:PingReq)
  private static final io.github.gravetii.grpc.PingReq DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.github.gravetii.grpc.PingReq();
  }

  public static io.github.gravetii.grpc.PingReq getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PingReq>
      PARSER = new com.google.protobuf.AbstractParser<PingReq>() {
    @java.lang.Override
    public PingReq parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new PingReq(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<PingReq> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PingReq> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.github.gravetii.grpc.PingReq getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

