// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: diztl.proto

package io.github.gravetii.grpc;

public interface UploadReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:UploadReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The node from which the requester node wants to download a file of interest.
   * </pre>
   *
   * <code>.Node source = 1;</code>
   */
  boolean hasSource();
  /**
   * <pre>
   * The node from which the requester node wants to download a file of interest.
   * </pre>
   *
   * <code>.Node source = 1;</code>
   */
  io.github.gravetii.grpc.Node getSource();
  /**
   * <pre>
   * The node from which the requester node wants to download a file of interest.
   * </pre>
   *
   * <code>.Node source = 1;</code>
   */
  io.github.gravetii.grpc.NodeOrBuilder getSourceOrBuilder();

  /**
   * <pre>
   * The metadata of the file to download.
   * </pre>
   *
   * <code>.FileMetadata metadata = 2;</code>
   */
  boolean hasMetadata();
  /**
   * <pre>
   * The metadata of the file to download.
   * </pre>
   *
   * <code>.FileMetadata metadata = 2;</code>
   */
  io.github.gravetii.grpc.FileMetadata getMetadata();
  /**
   * <pre>
   * The metadata of the file to download.
   * </pre>
   *
   * <code>.FileMetadata metadata = 2;</code>
   */
  io.github.gravetii.grpc.FileMetadataOrBuilder getMetadataOrBuilder();

  /**
   * <pre>
   * The upload contract that the receiver node wants to let the sender node know.
   * </pre>
   *
   * <code>.UploadContract contract = 3;</code>
   */
  boolean hasContract();
  /**
   * <pre>
   * The upload contract that the receiver node wants to let the sender node know.
   * </pre>
   *
   * <code>.UploadContract contract = 3;</code>
   */
  io.github.gravetii.grpc.UploadContract getContract();
  /**
   * <pre>
   * The upload contract that the receiver node wants to let the sender node know.
   * </pre>
   *
   * <code>.UploadContract contract = 3;</code>
   */
  io.github.gravetii.grpc.UploadContractOrBuilder getContractOrBuilder();
}
